Neos:
  Form:
    presets:
      'fusion':
        title: 'Fusion based Form Elements'
        parentPreset: 'default'
        formElementTypes:
          'Neos.Form:Base':
            renderingOptions:
              templatePathPattern: ~
              partialPathPattern: ~
              layoutPathPattern: ~
          'Neos.Form:Form':
            rendererClassName: 'Neos\Form\FusionRenderer\FusionFormRenderer'

    FusionRenderer:
      fusionAutoInclude:
        'Neos.Fusion': true
        'Neos.Form.FusionRenderer': true
      formHelper:
        mimeTypes:
          pdf: 'application/pdf'
          doc: 'application/msword'
          jpeg: 'image/jpeg'
          png: 'image/png'
          bmp: 'image/bmp'

  Neos:
    fusion:
      autoInclude:
        'Neos.Form.FusionRenderer': true

  Fusion:
    defaultContext:
      'Neos.Form.FusionRenderer': 'Neos\Form\FusionRenderer\Eel\Helper\FormHelper'
